version: "2"

services:  
  sqs:    
    image: localstack/localstack    
    ports:      
      - '4563-4599:4563-4599'      
      - '8055:8080'    
    environment:      
      SERVICES: sqs
      DATA_DIR: /tmp/localstack/data    
    volumes:      
      - 'sqs:/tmp/localstack'
  volumes:  
    sqs: null